Hopefully the last fix to get test passing

diff --git a/tests/get-reads-default-version-on-master/action.yaml b/tests/get-reads-default-version-on-master/action.yaml
--- a/tests/get-reads-default-version-on-master/action.yaml
+++ b/tests/get-reads-default-version-on-master/action.yaml
@@ -52,8 +52,8 @@ runs:
           exit 1
         fi
 
-        if ! [[ "$version" = "v0.1.0" ]]; then
-          echo "::error::Version should default to 0.1.0: $version"
+        if ! [[ "$version" = "0.0.1" ]]; then
+          echo "::error::Version should default to 0.0.1: $version"
           exit 1
         fi
 
